services:
  - docker:dind

stages:
  - build
  - test
  - deploy

unit-test:
  stage: build
  image: 
    name: maven:3.6.3-jdk-11-slim
  only:
    changes:
      - pom.xml
      - src/*
  script:
    - mvn verify
  artifacts:
    paths: [target/failsafe-reports/TEST-*.xml]
    when: always
    expire_in: one week
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml
  allow_failure: false

build-container:
  stage: build
  image:
    name: tmaier/docker-compose:latest
  only:
    changes:
      - Dockerfile
      - docker-compose.yml
      - pom.xml
      - src/*
  script:
   - docker-compose up -d --build
  allow_failure: false

functional-test:
  stage: test
  image:
    name: postman/newman
    entrypoint: [""]
  script:
    - newman run test/postman_collection.json -e test/postman_environment.json --insecure
  allow_failure: false

dast-tool_zap-basic:
  stage: test
  image:
    name: owasp/zap2docker-weekly
    entrypoint: [""]
  script:
    - /zap/zap-baseline.py -t http://hapi.fhir.org/baseR4 -J /zap/wrk/dast-tool_zap_baseline_scan-results.json
  rules: 
    - if: $DAST != "full"
      when: always
  artifacts:
    paths: [dast-tool_zap_baseline_scan-results.json]
    when: always
    expire_in: one week
  allow_failure: false

dast-tool_zap-full:
  stage: test
  image:
    name: owasp/zap2docker-weekly
  script:
    - /zap/zap-full-scan.py -t http://hapi.fhir.org/baseR4 -J /zap/wrk/dast-tool_zap_full_scan-results.json
  rules: 
    - if: $DAST == "full"
      when: always
  artifacts:
    paths: [dast-tool_zap_full_scan-results.json]
    when: always
    expire_in: one week
  allow_failure: false
