services:
  - docker:dind

stages:
  - build
  - test
  - deploy

unit-test:
  stage: build
  image: 
    name: maven:3.6.3-jdk-11-slim
  only:
    changes:
      - pom.xml
      - src/*
  script:
    - mvn verify
  artifacts:
    paths: [target/failsafe-reports/TEST-*.xml]
    when: always
    expire_in: one week
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml
  allow_failure: false

build-container:
  stage: build
  image:
    name: tmaier/docker-compose:latest
  only:
    changes:
      - Dockerfile
      - docker-compose.yml
      - pom.xml
      - src/*
  script:
   - docker-compose up -d --build
  allow_failure: false

functional-test:
  stage: test
  image:
    name: postman/newman
  script:
    - newman run $WORKDIR/test/postman_collection.json -e $WORKDIR/test/postman_environment.json --insecure
  allow_failure: false

dast-tool_zap-basic:
  stage: test
  image:
    name: owasp/zap2docker-weekly
  script:
    - docker run --user $(id -u):$(id -g) -w /zap -v $(pwd):/zap/wrk:rw --rm owasp/zap2docker-weekly zap-baseline.py -t https://hapi.f5labs.dev:8080/fhir -J dast-tool_zap_baseline_scan-results.json
  rules: 
    - if: $DAST != "full"
      when: always
  after_script:
    - docker rmi owasp/zap2docker-stable  # clean up the image to save the disk space
  artifacts:
    paths: [dast-tool_zap_baseline_scan-results.json]
    when: always
    expire_in: one week
  allow_failure: false

dast-tool_zap-full:
  stage: test
  image:
    name: owasp/zap2docker-weekly
  script:
    - docker run --user $(id -u):$(id -g) -w /zap -v $(pwd):/zap/wrk:rw --rm owasp/zap2docker-weekly zap-full-scan.py -t https://hapi.f5labs.dev:8080/fhir -J dast-tool_zap_full_scan-results.json
  rules: 
    - if: $DAST == "full"
      when: always
  after_script:
    - docker rmi owasp/zap2docker-stable  # clean up the image to save the disk space
  artifacts:
    paths: [dast-tool_zap_full_scan-results.json]
    when: always
    expire_in: one week
  allow_failure: false
