stages:
  - sec-pre_build
  - build
  - package
  - integration
  - release

include:
  - local: /.secops/sec-pre_build.gitlab-ci.yml
  - local: /.ci/test.gitlab-ci.yml
  - local: /.ci/build.gitlab-ci.yml
  - local: /.ci/package.gitlab-ci.yml
  - local: /.ci/integration.gitlab-ci.yml
  - local: /.ci/release.gitlab-ci.yml
