apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: hapi-fhir-mysql
  name: hapi-fhir-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hapi-fhir-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: hapi-fhir-mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: hapi
            - name: MYSQL_PASSWORD
              value: admin
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_USER
              value: admin
          image: mysql:latest
          name: hapi-fhir-mysql
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: hapi-fhir-mysql
      restartPolicy: Always
      volumes:
        - name: hapi-fhir-mysql
          persistentVolumeClaim:
            claimName: hapi-fhir-mysql
status: {}
