apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: hapi-fhir-jpaserver
  name: hapi-fhir-jpaserver
spec:
  containers:
    - image: hapi-fhir-jpaserver
      name: hapi-fhir-jpaserver
      ports:
        - containerPort: 8080
      resources: {}
  restartPolicy: OnFailure
status: {}
