services:
  - docker:dind

deploy-container:
  stage: deploy
  image:
    name: tmaier/docker-compose:latest
  variables:
    IMAGE_TAG: $CONTAINER_REGISRY/$CI_IMAGE:$CI_COMMIT_REF_SLUG
  script:
   - docker login $CONTAINER_REGISTRY -u $CONTAINER_REGISTRY_ID -p $CONTAINER_REGISTRY_PWD
   - docker-build -t hapi-fhir_jpaserver .
   - docker tag hapi-fhir-jpaserver:latest $IMAGE_TAG
   - docker push $IMAGE_TAG
  allow_failure: false
