services:
  - docker:dind

deploy-container:
  stage: deploy
  image:
    name: tmaier/docker-compose:latest
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
   - docker login $CONTAINER_REGISTRY -u $CONTAINER_REGISTRY_ID -p $CONTAINER_REGISTRY_PWD
   - docker-compose up -d --build 
   - docker push $IMAGE_TAG
  allow_failure: false
