services:
  - docker:dind

deploy-container:
  stage: deploy
  image:
    name: tmaier/docker-compose:latest
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
   - docker login $CONTAINER_REGISTRY -u $CONTAINER_REGISTRY_ID -p $CONTAINER_REGISTRY_PWD
   - docker-compose up -d --build 
   - docker tag hapi-fhir_hapi-fhir-jpaserver:latest 634994138577.dkr.ecr.ap-southeast-2.amazonaws.com/hapi-fhir_hapi-fhir-jpaserver:latest
   - docker push 634994138577.dkr.ecr.ap-southeast-2.amazonaws.com/hapi-fhir:latest
  allow_failure: false
