services:
  - docker:dind

deploy-container:
  stage: deploy
  image:
    name: tmaier/docker-compose:latest
  only:
    changes:
      - Dockerfile
      - docker-compose.yml
      - pom.xml
      - src/*
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
   - docker login $CONTAINER_REGISTRY -u $CONTAINER_REGISTRY_ID -p $CONTAINER_REGISTRY_PWD
   - docker-compose up -d --build -t $IMAGE_TAG
   - docker push $IMAGE_TAG
  allow_failure: false
