services:
  - docker:dind

deploy-container:
  stage: deploy
  image:
    name: tmaier/docker-compose:latest
  variables:
    IMAGE_TAG: $CONTAINER_REGISRY/$CI_IMAGE:$CI_COMMIT_REF_SLUG
  script:
   - docker login $CONTAINER_REGISTRY -u $CONTAINER_REGISTRY_ID -p $CONTAINER_REGISTRY_PWD
   - docker-compose up -d --build 
   - docker tag hapi-fhir_hapi-fhir-jpaserver:latest $CONTAINER_REGISTRY/hapi-fhir_jpaserver:latest
   - docker push $CONTAINER_REGISTRY/hapi-fhir_jpaserver:latest
  allow_failure: false
