services:
  - docker:dind

variables:
  APP_NAME: hapi-fhir_jpaserver

push-to-registry:
  stage: package
  image:
    name: docker:latest
  script:
   - docker build -t $APP_REGISTRY/$APP_NAME:$CI_COMMIT_TAG .
   - docker images
   - docker login --username $APP_REGISTRY_ID --password $APP_REGISTRY_PWD $APP_REGISTRY
   - docker push $APP_REGISTRY/$APP_NAME:$CI_COMMIT_TAG
  allow_failure: false
