services:
  - docker:dind

variables:
  APP_NAME: hapi-fhir_jpaserver
  DOCKER_HOST: tcp://docker:2375
push-to-registry:
  stage: package
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  before_script:
   - amazon-linux-extras install docker
   - aws --version
   - docker --version
  script:
   - docker build -t $APP_REGISTRY/$APP_NAME
   - docker images
   - docker login --username AWS --password $APP_REGISTRY_PWD
   - docker push $APP_REGISTRY/$APP_NAME:latest
  allow_failure: false
