services:
  - docker:dind

dast-tool_zap-basic:
  stage: release
  image:
    name: owasp/zap2docker-weekly
  before_script:
    - mkdir /zap/wrk
  script:
    - zap-baseline.py -t http://hapi.fhir.org/baseR4 -J dast-tool_zap_baseline_scan-results.json
  rules:
    - if: $DAST != "full"
      when: always
  artifacts:
    paths: [/zap/wrk/dast-tool_zap_baseline_scan-results.json]
    when: always
    expire_in: one week
  allow_failure: false

dast-tool_zap-full:
  stage: release
  image:
    name: owasp/zap2docker-weekly
  before_script:
    - mkdir /zap/wrk
  script:
    - zap-full-scan.py -t http://hapi.fhir.org/baseR4 -J dast-tool_zap_full_scan-results.json
  rules:
    - if: $DAST == "full"
      when: always
  artifacts:
    paths: [/zap/wrk/dast-tool_zap_full_scan-results.json]
    when: always
    expire_in: one week
  allow_failure: false