services:
  - docker:dind

sec-source_scan:
  stage: sec-pre_build
  image:
    name: shiftleft/scan
  script:
   - scan --src /src --type credscan,java,yaml --out_dir /app/reports
  artifacts:
   paths: [/app/reports/*]
   when: always
   expire_in: one week
  allow_failure: true

